nome=input("Qual é o seu nome")
print("Olá",nome,"É um prazer te conhecer")
input("clique em enter para continuar")
idade=input("Quantos anos você tem ?")
print("Que legal então você tem",idade,"anos")
input("clique em enter para continuar")
peso=input("E por fim , quanto você pesa ?")
print("Hm ... então você pesa",peso,"Kgs")
input("clique em enter para continuar")
print("Seu nome é",nome,"você tem",idade,"hm tá velho hein kkkk e você pesa",peso,"Kgs .... melhor nem comentar ......" )
input()